#!/bin/sh
pacman -S xorg-server xorg-xinit xorg-apps mesa openbox sddm alsa-lib alsa-utils asla-oss alsa-plugins ttf-liberation ttf-dejavu ttf-droid ttf-ubuntu-font-family papirus-icon-theme-git arc-dtk-theme zathura zathura-pdf-poppler zathura-djvu
